name: Publish Pull Request
on:
  pull_request:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.0' # Updated to use Node.js >=18.0.0

      - name: Install Expo CLI and EAS CLI using npm
        run: |
          npm install -g expo-cli eas-cli

      - name: Install dependencies
        run: yarn install

      - name: Publish to Expo
        run: NODE_ENV=dev expo publish --non-interactive --release-channel pr-${{ github.event.number }}

      - name: Add Expo link to PR
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const releaseChannel = `pr-${prNumber}`;
            const expoUrl = `https://expo.dev/@osandboxtester/minimilis?release-channel=${releaseChannel}`;
            const qrCodeUrl = `https://api.qrserver.com/v1/create-qr-code/?data=${encodeURIComponent(expoUrl)}&size=200x200`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `## Test this PR with Expo Go\n\nYour build has been published to Expo! 🎉\n\nScan the QR code below or click the link to open the app in Expo Go:\n\n🔗 [Open in Expo](${expoUrl})\n\n![Expo QR Code](${qrCodeUrl})`,
            });
