name: Publish Test Build
on:
  push:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x' # Compatible Node.js version

      - name: Install Dependencies
        run: |
          # Clean up old dependencies
          rm -rf node_modules package-lock.json
          npm cache clean --force

          # Install new Expo CLI and Metro config
          npm install --save-dev expo
          npm install metro-config @expo/metro-config
          npm install

      - name: Clear Expo Cache
        run: npx expo r -c

      - name: Debug Installed Packages
        run: npm list --depth=0

      - name: Check Expo CLI Version
        run: npx expo --version

      - name: Publish to Expo
        run: NODE_ENV=dev npx expo publish --non-interactive --release-channel test
