name: Publish Test Build
on:
  push:
    branches:
      - develop
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x' # Use a compatible Node.js version

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Clean and Install Dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install

      - name: Debug Installed Packages
        run: npm list --depth=0

      - name: Clear Expo Cache
        run: expo start --clear

      - name: Publish to Expo
        run: NODE_ENV=dev expo publish --non-interactive --release-channel test
