name: Publish Test Build
on:
  push:
    branches:
      - develop
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.0' # Downgrade to a supported version for expo-cli

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          expo-cache: true
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: |
          rm -rf node_modules
          npm cache clean --force
          npm install

      - name: Debug Installed Packages
        run: npm list --depth=0

      - name: Publish to Expo
        run: NODE_ENV=dev expo publish --non-interactive --release-channel test

      # - name: Add Expo link to PR
      #   uses: actions/github-script@v6
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     script: |
      #       const prNumber = context.payload.pull_request.number;
      #       const releaseChannel = `test`;
